language: node_js

addons:
  hosts:
    - graph.culturestake.local

services:
  - docker

node_js:
  - '11'

env:
  - PYTHON_VERSION=2.7.15 PYENV_TAG=v1.2.13 DOCKER_PATH=$HOME/lazaruslabs/culturestake-provisioning

before_install:
  # disable travis postgres
  - sudo /etc/init.d/postgresql stop

  # get latest pyenv version
  - cd $(pyenv root)
  - git fetch --all --tags
  - git checkout tags/$PYENV_TAG
  - cd $HOME

  # install python
  - pyenv install $PYTHON_VERSION -s
  - pyenv global $PYTHON_VERSION

  # get docker repository and copy configs
  - git clone https://github.com/lazaruslabs/circles-provisioning.git $DOCKER_PATH
  - cd $DOCKER_PATH
  - cp .env.example .env

  # container setup via docker-compose and migrate contracts
  - make build
  - make up

  # @TODO: uncomment when ready
  # - make contracts
  # - make subgraph

  # try starting failed services
  - make up

  # copy core configs
  - cd $TRAVIS_BUILD_DIR
  - cp .env.example .env

install:
  - npm install

script:
  - npm run test
  - npm run build
